# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pythonGUI/Tran.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pandas as pd
import xlrd
import csv
import codecs


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Tran(QtWidgets.QMainWindow):
      # 为了使类继承父类中的内容
    def __init__(self):
        super(Ui_Tran,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
    ###########
    def setupUi(self, Tran):
        Tran.setObjectName("Tran")
        Tran.setEnabled(True)
        Tran.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(Tran)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(220, 80, 500, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 160, 500, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 60, 107, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 360, 72, 15))
        self.label_3.setObjectName("label_3")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(90, 230, 101, 47))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        Tran.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        Tran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tran)
        self.statusbar.setObjectName("statusbar")
        Tran.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.tran)# 点击链接到tran方法
        
        self.retranslateUi(Tran)
        self.checkBox.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.checkBox.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        self.checkBox.toggled['bool'].connect(self.checkBox_2.setDisabled)
        self.checkBox_2.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.checkBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Tran)
    # 实现该页面的功能
    def tran(self):
        if self.checkBox.isChecked(): # 第一个盒子激活
            self.csv_to_xlsx(self.lineEdit.text(),self.lineEdit_2.text())
        if self.checkBox_2.isChecked():
            self.xlsx_to_csv(self.lineEdit.text(),self.lineEdit_2.text())

            
    # csv文件转为excel文件
    def csv_to_xlsx(self,path,file_name):   # 图形界面中不可使用input输入，会导致死循环
        csv_1 = pd.read_csv(path, encoding='utf-8')
        sheet_name = "Sheet1"
        csv_1.to_excel(f'{file_name}.xlsx', sheet_name=f'{sheet_name}')
        self.label_3.setText("成功")
    
        
    # excel文件转换为csv文件
    def xlsx_to_csv(self,path,name):
        workbook = xlrd.open_workbook(path)
        table = workbook.sheet_by_index(0)
        with codecs.open(f'{name}.csv', 'w', encoding='utf-8') as f:
            write = csv.writer(f)
            for row_num in range(table.nrows):
                row_value = table.row_values(row_num)
                write.writerow(row_value)
    ###############################    
    def retranslateUi(self, Tran):
        _translate = QtCore.QCoreApplication.translate
        Tran.setWindowTitle(_translate("Tran", "MainWindow"))
        self.pushButton.setText(_translate("Tran", "转换"))
        self.label.setText(_translate("Tran", "待转换文件路径"))
        self.label_2.setText(_translate("Tran", "转换后文件名"))
        self.label_3.setText(_translate("Tran", "     "))
        self.checkBox.setText(_translate("Tran", "CSV->xlsx"))
        self.checkBox_2.setText(_translate("Tran", "xlsx->CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tran = QtWidgets.QMainWindow()
    ui = Ui_Tran()
    ui.setupUi(Tran)
    Tran.show()
    sys.exit(app.exec_())
